"""ViewerTemplateBuilder: index.html / viewer.css / app.js を生成する専用クラス。"""


class ViewerTemplateBuilder:
    """テンプレート生成専用。index.html, viewer.css, app.js を lines で組み立てて返す。"""

    def render_index_html(self) -> str:
        lines = [
            "<!DOCTYPE html>",
            "<html lang=\"ja\">",
            "<head>",
            "<meta charset=\"utf-8\">",
            "<title>RAN Liaison Sankey</title>",
            "<script src=\"https://cdn.plot.ly/plotly-2.35.0.min.js\"></script>",
            "<link rel=\"stylesheet\" href=\"viewer.css\">",
            "</head>",
            "<body>",
            "<div class=\"controls\">",
            "  <label for=\"dir\">Direction:</label>",
            "  <select id=\"dir\">",
            "    <option value=\"all\">All</option>",
            "    <option value=\"in\">In</option>",
            "    <option value=\"out\">Out</option>",
            "  </select>",
            "  <label>Meeting:</label>",
            "  <div class=\"radio-group\" id=\"meetings\"></div>",
            "  <label class=\"toggle-wrap\">",
            "    <input type=\"checkbox\" id=\"splitOut\" />",
            "    <span>Split LS out by recipients (1/k)</span>",
            "  </label>",
            "  <div class=\"legend\">",
            "    <span class=\"legend-item\"><span class=\"legend-swatch in\"></span> LS in</span>",
            "    <span class=\"legend-item\"><span class=\"legend-swatch out\"></span> LS out</span>",
            "  </div>",
            "</div>",
            "<div id=\"chart\"></div>",
            "<div id=\"modal\" class=\"modal hidden\" tabindex=\"-1\" role=\"dialog\">",
            "  <div class=\"modal-content\">",
            "    <div class=\"modal-header\">",
            "      <h3 id=\"modalTitle\">Flow detail</h3>",
            "      <button type=\"button\" id=\"modalClose\" class=\"modal-close\">Close</button>",
            "    </div>",
            "    <div class=\"modal-body\">",
            "      <p id=\"modalFromTo\"></p>",
            "      <p id=\"modalTotal\"></p>",
            "      <table id=\"modalTable\">",
            "        <thead><tr><th>Meeting</th><th>Raw</th><th>Displayed</th></tr></thead>",
            "        <tbody></tbody>",
            "      </table>",
            "    </div>",
            "  </div>",
            "</div>",
            "<script src=\"data.js\"></script>",
            "<script src=\"app.js\"></script>",
            "</body>",
            "</html>",
        ]
        return "\n".join(lines)

    def render_viewer_css(self) -> str:
        lines = [
            "* { box-sizing: border-box; margin: 0; padding: 0; }",
            "body { font-family: \"Segoe UI\", Arial, sans-serif; background: #f5f6fa; color: #222; }",
            ".controls {",
            "  display: flex; align-items: center; gap: 16px; flex-wrap: wrap;",
            "  padding: 12px 20px; background: #fff; border-bottom: 1px solid #ddd;",
            "  position: sticky; top: 0; z-index: 10;",
            "}",
            ".controls label { font-weight: 600; font-size: 14px; }",
            ".controls select { padding: 6px 12px; border: 1px solid #bbb; border-radius: 6px; font-size: 14px; cursor: pointer; }",
            ".radio-group { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }",
            ".radio-group label { font-weight: 400; cursor: pointer; padding: 4px 10px;",
            "  border: 1px solid #ccc; border-radius: 16px; font-size: 13px; }",
            ".radio-group input { display: none; }",
            ".radio-group input:checked + span { background: #3b82f6; color: #fff; border-radius: 16px;",
            "  padding: 4px 10px; margin: -4px -10px; }",
            ".toggle-wrap { font-weight: 400; font-size: 13px; }",
            ".toggle-wrap input { margin-right: 6px; }",
            ".legend { display: flex; gap: 12px; margin-left: auto; font-size: 13px; }",
            ".legend-swatch { width: 14px; height: 8px; border-radius: 3px; display: inline-block; margin-right: 4px; }",
            ".legend-swatch.in { background: rgba(31,119,180,0.55); }",
            ".legend-swatch.out { background: rgba(255,127,14,0.55); }",
            "#chart { width: 100%; min-height: calc(100vh - 56px); }",
            ".modal { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 100;",
            "  display: flex; align-items: center; justify-content: center; }",
            ".modal.hidden { display: none; }",
            ".modal-content { background: #fff; border-radius: 8px; max-width: 480px; width: 90%;",
            "  max-height: 80vh; overflow: auto; box-shadow: 0 4px 20px rgba(0,0,0,0.15); }",
            ".modal-header { display: flex; justify-content: space-between; align-items: center;",
            "  padding: 12px 16px; border-bottom: 1px solid #eee; }",
            ".modal-header h3 { font-size: 16px; }",
            ".modal-close { padding: 6px 12px; cursor: pointer; border: 1px solid #ccc; border-radius: 6px;",
            "  background: #fff; }",
            ".modal-body { padding: 16px; }",
            ".modal-body p { margin-bottom: 8px; font-size: 14px; }",
            ".modal-body table { width: 100%; border-collapse: collapse; font-size: 13px; }",
            ".modal-body th, .modal-body td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #eee; }",
        ]
        return "\n".join(lines)

    def render_app_js(self, debug: bool = False) -> str:
        """app.js を生成。Problem1/2 対応: Plotly API で plotly_click, edge_key 照合, hovertemplate."""
        lines = [
            "(function() {",
            "  const debugMode = " + ("true" if debug else "false") + ";",
            "  if (typeof window.LIAISON_DATA === \"undefined\") {",
            "    console.error(\"LIAISON_DATA not found. Load data.js first.\"); return;",
            "  }",
            "  const { meetings: meetingList, edgesByMeeting, edgesTotal } = window.LIAISON_DATA;",
            "  const COLOR_IN = \"rgba(31,119,180,0.55)\";",
            "  const COLOR_OUT = \"rgba(255,127,14,0.55)\";",
            "  const state = { dir: \"all\", meeting: \"all\", splitOut: false };",
            "",
            "  const dirEl = document.getElementById(\"dir\");",
            "  const meetingsEl = document.getElementById(\"meetings\");",
            "  const splitOutEl = document.getElementById(\"splitOut\");",
            "  const chartEl = document.getElementById(\"chart\");",
            "  const modalEl = document.getElementById(\"modal\");",
            "  const modalTitle = document.getElementById(\"modalTitle\");",
            "  const modalFromTo = document.getElementById(\"modalFromTo\");",
            "  const modalTotal = document.getElementById(\"modalTotal\");",
            "  const modalTableBody = document.querySelector(\"#modalTable tbody\");",
            "  function closeModal() { modalEl.classList.add(\"hidden\"); }",
            "  document.getElementById(\"modalClose\").addEventListener(\"click\", closeModal);",
            "  modalEl.addEventListener(\"click\", (e) => { if (e.target === modalEl) closeModal(); });",
            "  document.addEventListener(\"keydown\", (e) => { if (e.key === \"Escape\" && !modalEl.classList.contains(\"hidden\")) closeModal(); });",
            "",
            "  meetingsEl.innerHTML = \"\";",
            "  function addRadio(value, label) {",
            "    const lbl = document.createElement(\"label\");",
            "    const inp = document.createElement(\"input\");",
            "    inp.type = \"radio\"; inp.name = \"meeting\"; inp.value = value;",
            "    if (value === \"all\") inp.checked = true;",
            "    const sp = document.createElement(\"span\"); sp.textContent = label;",
            "    lbl.appendChild(inp); lbl.appendChild(sp);",
            "    inp.addEventListener(\"change\", () => { state.meeting = value; render(); });",
            "    meetingsEl.appendChild(lbl);",
            "  }",
            "  addRadio(\"all\", \"all\");",
            "  meetingList.forEach(m => addRadio(m, m));",
            "  dirEl.addEventListener(\"change\", e => { state.dir = e.target.value; render(); });",
            "  splitOutEl.addEventListener(\"change\", e => { state.splitOut = e.target.checked; render(); });",
            "",
            "  function edgesToSankey(edges, dir, useSplit) {",
            "    const edgeMap = {};",
            "    edges.forEach(e => {",
            "      const from_ = e.from, to_ = e.to, ek = e.edge_key;",
            "      const w = dir === \"out\" && useSplit ? Number(e.weight_split) : Number(e.weight_raw);",
            "      const key = from_ + \"|||\" + to_;",
            "      if (!edgeMap[key]) {",
            "        edgeMap[key] = { from: from_, to: to_, weight: 0, color: dir === \"in\" ? COLOR_IN : COLOR_OUT,",
            "          edge_key: ek };",
            "      }",
            "      edgeMap[key].weight += w;",
            "    });",
            "    const edgesArr = Object.values(edgeMap).filter(x => x.weight > 0);",
            "    if (edgesArr.length === 0) {",
            "      return { node: { label: [\"RAN\"], color: [\"#555\"] },",
            "        link: { source: [], target: [], value: [], color: [], customdata: [] } };",
            "    }",
            "    const nodeSet = new Set();",
            "    edgesArr.forEach(e => { nodeSet.add(e.from); nodeSet.add(e.to); });",
            "    const labels = [\"RAN\", ...[...nodeSet].filter(n => n !== \"RAN\").sort()];",
            "    const idx = Object.fromEntries(labels.map((l, i) => [l, i]));",
            "    const nodeColors = labels.map(l => l === \"RAN\" ? \"#555\" :",
            "      l.endsWith(\"(src)\") ? \"rgba(31,119,180,0.8)\" : \"rgba(255,127,14,0.8)\");",
            "    const hoverFmt = dir === \"out\" && useSplit ? \"Displayed: %{value:.2f}\" : \"Displayed: %{value:.0f}\";",
            "    return {",
            "      node: { label: labels, color: nodeColors, pad: 20, thickness: 18 },",
            "      link: {",
            "        source: edgesArr.map(e => idx[e.from]),",
            "        target: edgesArr.map(e => idx[e.to]),",
            "        value: edgesArr.map(e => e.weight),",
            "        color: edgesArr.map(e => e.color),",
            "        customdata: edgesArr.map(e => e.edge_key),",
            "        hovertemplate: hoverFmt,",
            "      },",
            "    };",
            "  }",
            "",
            "  function buildTraces() {",
            "    const useMeeting = state.meeting;",
            "    const dataSource = useMeeting === \"all\" ? edgesTotal :",
            "      edgesByMeeting.filter(e => e.meeting === useMeeting);",
            "    const useSplit = state.splitOut;",
            "",
            "    if (state.dir === \"in\") {",
            "      const edgesIn = dataSource.filter(e => e.dir === \"in\");",
            "      const s = edgesToSankey(edgesIn, \"in\", false);",
            "      return [{ type: \"sankey\", orientation: \"h\", ...s, name: \"Inbound\", meta: { dir: \"in\" } }];",
            "    }",
            "    if (state.dir === \"out\") {",
            "      const edgesOut = dataSource.filter(e => e.dir === \"out\");",
            "      const s = edgesToSankey(edgesOut, \"out\", useSplit);",
            "      return [{ type: \"sankey\", orientation: \"h\", ...s, name: \"Outbound\", meta: { dir: \"out\" } }];",
            "    }",
            "    const edgesIn = dataSource.filter(e => e.dir === \"in\");",
            "    const edgesOut = dataSource.filter(e => e.dir === \"out\");",
            "    const sIn = edgesToSankey(edgesIn, \"in\", false);",
            "    const sOut = edgesToSankey(edgesOut, \"out\", useSplit);",
            "    return [",
            "      { type: \"sankey\", orientation: \"h\", ...sIn, name: \"Inbound\",",
            "        domain: { x: [0, 0.48], y: [0, 1] }, meta: { dir: \"in\" } },",
            "      { type: \"sankey\", orientation: \"h\", ...sOut, name: \"Outbound\",",
            "        domain: { x: [0.52, 1], y: [0, 1] }, meta: { dir: \"out\" } },",
            "    ];",
            "  }",
            "",
            "  function getLayout() {",
            "    const twoPanel = state.dir === \"all\";",
            "    return {",
            "      title: { text: twoPanel ? \"Inbound (left) | Outbound (right)\" :",
            "        state.dir === \"in\" ? \"Inbound\" : \"Outbound\", font: { size: 16 } },",
            "      font: { size: 11 }, margin: { l: 20, r: 20, t: 50, b: 20 },",
            "      paper_bgcolor: \"#f5f6fa\", showlegend: false,",
            "    };",
            "  }",
            "",
            "  function render() {",
            "    const traces = buildTraces();",
            "    const layout = getLayout();",
            "    Plotly.react(chartEl, traces, layout, { responsive: true }).then(() => {",
            "      if (chartEl.removeAllListeners) chartEl.removeAllListeners(\"plotly_click\");",
            "      chartEl.on(\"plotly_click\", onPlotClick);",
            "    });",
            "  }",
            "",
            "  function extractLinkIndex(pt) {",
            "    const trace = pt.data;",
            "    if (!trace || !trace.link || !Array.isArray(trace.link.source)) return -1;",
            "    const n = trace.link.source.length;",
            "    let idx = pt.pointNumber;",
            "    if (typeof idx === \"number\" && idx >= 0 && idx < n) return idx;",
            "    idx = pt.pointIndex;",
            "    if (typeof idx === \"number\" && idx >= 0 && idx < n) return idx;",
            "    idx = pt.linkIndex;",
            "    if (typeof idx === \"number\" && idx >= 0 && idx < n) return idx;",
            "    return -1;",
            "  }",
            "",
            "  function extractEdgeKey(pt) {",
            "    if (!pt || !pt.data) return null;",
            "    const trace = pt.data;",
            "    if (!trace.link || !Array.isArray(trace.link.source)) return null;",
            "    const linkIndex = extractLinkIndex(pt);",
            "    if (linkIndex < 0 || linkIndex >= trace.link.source.length) return null;",
            "    if (pt.customdata != null && pt.customdata !== \"\") return pt.customdata;",
            "    const cd = trace.link.customdata;",
            "    if (Array.isArray(cd) && cd[linkIndex] != null && cd[linkIndex] !== \"\") return cd[linkIndex];",
            "    return null;",
            "  }",
            "",
            "  function onPlotClick(ev) {",
        ]
        if debug:
            lines.extend([
                "    if (typeof console !== \"undefined\") {",
                "      console.log(\"plotly_click\", ev);",
                "      if (ev.points && ev.points[0]) {",
                "        const p = ev.points[0];",
                "        console.log(\"pt keys\", Object.keys(p));",
                "        console.log(\"pt.pointNumber\", p.pointNumber);",
                "        console.log(\"has trace.link.customdata\", !!(p.data && p.data.link && p.data.link.customdata));",
                "      }",
                "    }",
            ])
        lines.extend([
            "    if (!ev.points || ev.points.length === 0) return;",
            "    const pt = ev.points[0];",
            "    const edgeKey = extractEdgeKey(pt);",
            "    if (debugMode && typeof console !== \"undefined\") console.log(\"edgeKey\", edgeKey);",
            "    if (!edgeKey) return;",
            "    const trace = pt.data;",
            "    const dir = (trace.meta && trace.meta.dir) || \"out\";",
            "    const rows = state.meeting === \"all\" ? edgesByMeeting :",
            "      edgesByMeeting.filter(e => e.meeting === state.meeting);",
            "    const filtered = rows.filter(e => e.edge_key === edgeKey);",
            "    if (filtered.length === 0) {",
            "      modalTitle.textContent = (dir === \"in\" ? \"Inbound\" : \"Outbound\") + \" flow detail\";",
            "      modalFromTo.textContent = \"edge_key: \" + edgeKey;",
            "      modalTotal.textContent = \"該当データなし\";",
            "      modalTableBody.innerHTML = \"<tr><td colspan=\\\"3\\\">該当データなし</td></tr>\";",
            "      modalEl.classList.remove(\"hidden\");",
            "      return;",
            "    }",
            "    const from_ = filtered[0].from, to_ = filtered[0].to;",
            "    let rawSum = 0, dispSum = 0;",
            "    const byMeeting = [];",
            "    filtered.forEach(e => {",
            "      rawSum += Number(e.raw_count);",
            "      const d = state.splitOut && dir === \"out\" ? Number(e.weight_split) : Number(e.weight_raw);",
            "      dispSum += d;",
            "      byMeeting.push({ meeting: e.meeting, raw: Number(e.raw_count), disp: d });",
            "    });",
            "    modalTitle.textContent = (dir === \"in\" ? \"Inbound\" : \"Outbound\") + \" flow detail\";",
            "    modalFromTo.textContent = \"From: \" + from_ + \" → To: \" + to_;",
            "    modalTotal.textContent = \"Raw: \" + rawSum + \", Displayed: \" + dispSum.toFixed(2);",
            "    modalTableBody.innerHTML = byMeeting.map(r => {",
            "      const disp = r.disp % 1 === 0 ? r.disp : r.disp.toFixed(2);",
            "      return \"<tr><td>\" + r.meeting + \"</td><td>\" + r.raw + \"</td><td>\" + disp + \"</td></tr>\";",
            "    }).join(\"\");",
            "    modalEl.classList.remove(\"hidden\");",
            "  }",
            "",
            "  render();",
            "})();",
        ])
        return "\n".join(lines)
